import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { context } from 'esbuild';

/**
 * Writes THIRD-PARTY-NOTICES.md from what the bundles actually contain.
 *
 * Every library Docx bundles is under a permissive licence, and every one
 * of those licences asks for the same thing: that its notice travels with the
 * copies. The list is read from the esbuild metafiles rather than from
 * package.json, so it describes what is really shipped rather than what is
 * merely installed.
 */

const BUNDLES = [
  {
    entryPoints: ['src/extension.ts'],
    platform: 'node',
    format: 'cjs',
    external: ['vscode'],
  },
  {
    entryPoints: ['webview-src/main.ts'],
    platform: 'browser',
    format: 'iife',
    loader: { '.ttf': 'file' },
    define: { 'process.env.NODE_ENV': '"production"' },
  },
];

async function bundledPackages() {
  const names = new Set();
  for (const config of BUNDLES) {
    const ctx = await context({
      ...config,
      outfile: '/dev/null',
      bundle: true,
      minify: true,
      metafile: true,
      write: false,
      target: 'es2022',
      logLevel: 'silent',
    });
    const { metafile } = await ctx.rebuild();
    await ctx.dispose();
    for (const input of Object.keys(metafile.inputs)) {
      const match = /^node_modules\/((?:@[^/]+\/)?[^/]+)\//.exec(input);
      if (match?.[1]) {
        names.add(match[1]);
      }
    }
  }
  return [...names].sort();
}

function licenceText(name) {
  const directory = `node_modules/${name}`;
  const file = readdirSync(directory).find((entry) => /^(LICENSE|LICENCE|COPYING)/i.test(entry));
  return file ? readFileSync(`${directory}/${file}`, 'utf8').trim() : undefined;
}

const packages = await bundledPackages();
const sections = [
  '# Third-party notices',
  '',
  'Docx bundles the libraries below into the files it ships. Each is under a',
  'permissive licence, and each of those licences asks that its notice travels',
  'with the copies — which is what this file is.',
  '',
  'Generated by `npm run generate:notices` from what the bundles actually contain.',
  '',
];

const rows = ['| Package | Version | Licence |', '| --- | --- | --- |'];
const bodies = [];
for (const name of packages) {
  const manifest = JSON.parse(readFileSync(`node_modules/${name}/package.json`, 'utf8'));
  const licence = manifest.license ?? '(see below)';
  rows.push(`| \`${name}\` | ${manifest.version} | ${licence} |`);

  const text = licenceText(name);
  bodies.push(`## ${name} ${manifest.version}\n\nLicence: ${licence}\n`);
  bodies.push(text
    ? `\`\`\`\n${text}\n\`\`\`\n`
    : `The package ships no licence file. Its manifest declares ${licence}.\n`);
}

writeFileSync(
  'THIRD-PARTY-NOTICES.md',
  `${[...sections, ...rows, '', ...bodies].join('\n').replaceAll(/\n{3,}/g, '\n\n')}\n`,
);
console.log(`Wrote THIRD-PARTY-NOTICES.md for ${packages.length} bundled packages.`);
