import { strict as assert } from 'node:assert';
import { copyFile, mkdtemp, readFile, realpath, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import * as path from 'node:path';
import * as vscode from 'vscode';
import { after, afterEach, before, describe, it } from 'mocha';
import {
  mirrorContents,
  mirrorUriFor,
  refreshExistingMirror,
} from '../../src/mirror/markdownMirror';

/**
 * The rule this feature lives by: it refreshes a mirror that exists and never
 * creates one. It writes to the user's repository, so that is the behaviour
 * worth testing against the real file system rather than a stub.
 */
describe('Keeping a Markdown mirror up to date', () => {
  let folder: string;
  let fixtures: string;

  const host = {
    read: async (uri: vscode.Uri) => new Uint8Array(await readFile(uri.fsPath)),
  };

  before(async function () {
    this.timeout(60_000);
    const extension = vscode.extensions.getExtension('showdocx.docx');
    assert.ok(extension, 'Expected the Docx extension to be installed.');
    await extension.activate();
    fixtures = path.join(extension.extensionPath, 'test', 'fixtures');
    folder = await mkdtemp(path.join(await realpath(tmpdir()), 'showdocx-mirror-'));
  });

  afterEach(async () => {
    await vscode.workspace.getConfiguration('docx').update(
      'markdownMirror',
      undefined,
      vscode.ConfigurationTarget.Global,
    );
  });

  after(async () => {
    await rm(folder, { recursive: true, force: true, maxRetries: 10, retryDelay: 250 });
  });

  async function document(name: string): Promise<vscode.Uri> {
    const target = path.join(folder, name);
    await copyFile(path.join(fixtures, 'simple.docx'), target);
    return vscode.Uri.file(target);
  }

  async function setMode(mode: string): Promise<void> {
    await vscode.workspace.getConfiguration('docx').update(
      'markdownMirror',
      mode,
      vscode.ConfigurationTarget.Global,
    );
  }

  it('does not create a mirror for a document that has none', async function () {
    this.timeout(60_000);
    await setMode('onChange');
    const source = await document('untouched.docx');

    const wrote = await refreshExistingMirror(source, host);

    assert.equal(wrote, false);
    // The whole rule: a viewer must not add files to someone's repository.
    await assert.rejects(readFile(path.join(folder, 'untouched.md')));
  });

  it('rewrites a mirror that is already there', async function () {
    this.timeout(60_000);
    await setMode('onChange');
    const source = await document('mirrored.docx');
    const mirror = path.join(folder, 'mirrored.md');
    await writeFile(mirror, 'stale contents');

    const wrote = await refreshExistingMirror(source, host);

    assert.equal(wrote, true);
    const contents = await readFile(mirror, 'utf8');
    assert.ok(contents.includes('Docx Sample'), contents.slice(0, 200));
    assert.ok(!contents.includes('stale contents'));
  });

  it('does nothing at all while the setting is off', async function () {
    this.timeout(60_000);
    await setMode('off');
    const source = await document('disabled.docx');
    const mirror = path.join(folder, 'disabled.md');
    await writeFile(mirror, 'left alone');

    const wrote = await refreshExistingMirror(source, host);

    assert.equal(wrote, false);
    assert.equal(await readFile(mirror, 'utf8'), 'left alone');
  });

  it('says what a mirror is and where it came from', async function () {
    this.timeout(60_000);
    await setMode('onChange');
    const source = await document('labelled.docx');
    const mirror = path.join(folder, 'labelled.md');
    await writeFile(mirror, '');

    await refreshExistingMirror(source, host);

    // Anyone meeting this file in a pull request should see in a second that it
    // is generated and which document it came from.
    const contents = await readFile(mirror, 'utf8');
    assert.match(contents, /Generated by Docx from labelled\.docx/);
    assert.match(contents, /Edit the document, not this file/);
  });
});

describe('Where a mirror belongs', () => {
  const source = vscode.Uri.file(path.join(path.sep, 'repo', 'docs', 'spec.docx'));

  it('sits beside the document by default', () => {
    const mirror = mirrorUriFor(source, '');
    assert.equal(path.posix.basename(mirror.path), 'spec.md');
    assert.equal(path.posix.dirname(mirror.path), path.posix.dirname(source.path));
  });

  it('names a mirror after the document, whichever Word type it is', () => {
    for (const name of ['form.docm', 'letterhead.dotx', 'macro.dotm']) {
      const document = source.with({ path: `/repo/${name}` });
      assert.equal(path.posix.basename(mirrorUriFor(document, '').path), `${name.split('.')[0]}.md`);
    }
  });

  it('labels the mirror with the document it came from', () => {
    assert.match(mirrorContents(source, 'body'), /^<!-- Generated by Docx from spec\.docx/);
    assert.ok(mirrorContents(source, 'body').endsWith('body'));
  });
});
