communityBaseUrl: "https://lab-test.cloudlab.top/api/v0.3"
communityPageBaseUrl: "https://test.cloudlab.top"
codeTestUrl: "https://quiz-test.cloudlab.top"
codePlayerUrl: "https://run-test.cloudlab.top"
